8.94939e-28	8.35036e-28	9.41393e-28	-1.46864e-27	-1.48266e-27	-1.47408e-27	9.26929e-28	8.27151e-28	
1.46734e-16	9.23291e-17	-4.3113e-17	-6.30997e-17	-1.02813e-16	-5.76109e-17	-5.47371e-17	8.23097e-17	
1.02645e+06	621562	-77714.4	-937701	-850384	-714419	275183	657027	
1.22055e+50	4.41996e+49	-4.71845e+49	-8.10857e+49	-9.32608e+49	-4.08313e+49	8.91278e+48	8.71949e+49	
-3.98221e+137	-9.88882e+137	-5.57691e+137	3.60743e+137	8.8358e+137	5.45868e+137	2.58476e+137	-1.03873e+137	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
nan	nan	nan	nan	nan	nan	nan	nan	
